### ISSUE TITLE
Null check

### ISSUE THREAD

**Issue by kometenstaub** [chrisgrieser/obsidian-footnote-indicator#1]
This could be `null`. 

https://github.com/chrisgrieser/obsidian-footnote-indicator/blob/a7986c0c62481a539cb7c69fa64883cecccb988e/main.ts#L34

I'm not sure whether the check in line 37 is enough, javalent had noted something similar in #plugin-dev for another plugin. 

https://github.com/obsidianmd/obsidian-api/blob/342a49dcc4e2012e4c60e16a5a3d16d740ad86b6/obsidian.d.ts#L3622

**Comment by chrisgrieser** [comment]
then what should be the check?

PS: feel free to make a PR :)

**Comment by chrisgrieser** [comment]
done
