### ISSUE TITLE
Debounce `editor-change` events

### ISSUE THREAD

**Issue by kometenstaub** [chrisgrieser/obsidian-footnote-indicator#2]
I would debounce the `editor-change` events so that they only run once the user has stopped typing for a certain amount of time.

**Comment by chrisgrieser** [comment]
fixed with 0.2.1

**Comment by kometenstaub** [comment]
I think you'd need to add `true` if I read pjeby's comment here correctly.

https://github.com/obsidianmd/obsidian-releases/pull/732#issuecomment-1013805287

**Comment by chrisgrieser** [comment]
done
